//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APSWs
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ranking", Namespace="http://www.apusaq.com/APS/DataContract")]
    public partial class Ranking : object
    {
        
        private string ApellidosField;
        
        private string CategoriaField;
        
        private string NombresField;
        
        private int puestoField;
        
        private int puntajeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos
        {
            get
            {
                return this.ApellidosField;
            }
            set
            {
                this.ApellidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Categoria
        {
            get
            {
                return this.CategoriaField;
            }
            set
            {
                this.CategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int puesto
        {
            get
            {
                return this.puestoField;
            }
            set
            {
                this.puestoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int puntaje
        {
            get
            {
                return this.puntajeField;
            }
            set
            {
                this.puntajeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuadro", Namespace="http://www.apusaq.com/APS/DataContract")]
    public partial class Cuadro : object
    {
        
        private string P1Field;
        
        private int P1idField;
        
        private string P2Field;
        
        private int P2idField;
        
        private string categoriaField;
        
        private int ganadorField;
        
        private string nombreField;
        
        private string resultadoField;
        
        private int rondaField;
        
        private string torneoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P1
        {
            get
            {
                return this.P1Field;
            }
            set
            {
                this.P1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int P1id
        {
            get
            {
                return this.P1idField;
            }
            set
            {
                this.P1idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string P2
        {
            get
            {
                return this.P2Field;
            }
            set
            {
                this.P2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int P2id
        {
            get
            {
                return this.P2idField;
            }
            set
            {
                this.P2idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string categoria
        {
            get
            {
                return this.categoriaField;
            }
            set
            {
                this.categoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ganador
        {
            get
            {
                return this.ganadorField;
            }
            set
            {
                this.ganadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ronda
        {
            get
            {
                return this.rondaField;
            }
            set
            {
                this.rondaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string torneo
        {
            get
            {
                return this.torneoField;
            }
            set
            {
                this.torneoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categoria", Namespace="http://www.apusaq.com/APS/DataContract")]
    public partial class Categoria : object
    {
        
        private string TipoField;
        
        private string cCategoriaField;
        
        private string cTorneoField;
        
        private int cuposField;
        
        private int idTcategoriaField;
        
        private int rondaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cCategoria
        {
            get
            {
                return this.cCategoriaField;
            }
            set
            {
                this.cCategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cTorneo
        {
            get
            {
                return this.cTorneoField;
            }
            set
            {
                this.cTorneoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cupos
        {
            get
            {
                return this.cuposField;
            }
            set
            {
                this.cuposField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTcategoria
        {
            get
            {
                return this.idTcategoriaField;
            }
            set
            {
                this.idTcategoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ronda
        {
            get
            {
                return this.rondaField;
            }
            set
            {
                this.rondaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/APS.WS")]
    public partial class CompositeType : object
    {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="APSWs.ITService")]
    public interface ITService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITService/GetRanking", ReplyAction="http://tempuri.org/ITService/GetRankingResponse")]
        System.Threading.Tasks.Task<APSWs.Ranking[]> GetRankingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITService/GetRanking1", ReplyAction="http://tempuri.org/ITService/GetRanking1Response")]
        System.Threading.Tasks.Task<string> GetRanking1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITService/GetUltimos", ReplyAction="http://tempuri.org/ITService/GetUltimosResponse")]
        System.Threading.Tasks.Task<APSWs.Cuadro[]> GetUltimosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITService/GetUltimos1", ReplyAction="http://tempuri.org/ITService/GetUltimos1Response")]
        System.Threading.Tasks.Task<string> GetUltimos1Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITService/GetData", ReplyAction="http://tempuri.org/ITService/GetDataResponse")]
        System.Threading.Tasks.Task<APSWs.Categoria[]> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITService/GetData1", ReplyAction="http://tempuri.org/ITService/GetData1Response")]
        System.Threading.Tasks.Task<string> GetData1Async(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITService/GetCuadro", ReplyAction="http://tempuri.org/ITService/GetCuadroResponse")]
        System.Threading.Tasks.Task<APSWs.Cuadro[]> GetCuadroAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITService/GetCuadro1", ReplyAction="http://tempuri.org/ITService/GetCuadro1Response")]
        System.Threading.Tasks.Task<string> GetCuadro1Async(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITService/GetPartidos", ReplyAction="http://tempuri.org/ITService/GetPartidosResponse")]
        System.Threading.Tasks.Task<APSWs.Cuadro[]> GetPartidosAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITService/GetPartidos1", ReplyAction="http://tempuri.org/ITService/GetPartidos1Response")]
        System.Threading.Tasks.Task<string> GetPartidos1Async(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITService/GuardarResultado", ReplyAction="http://tempuri.org/ITService/GuardarResultadoResponse")]
        System.Threading.Tasks.Task<int> GuardarResultadoAsync(int value, string resultado, int ganador, int WO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITService/GetH2H", ReplyAction="http://tempuri.org/ITService/GetH2HResponse")]
        System.Threading.Tasks.Task<APSWs.Cuadro[]> GetH2HAsync(int value, int value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITService/GetH2H1", ReplyAction="http://tempuri.org/ITService/GetH2H1Response")]
        System.Threading.Tasks.Task<string> GetH2H1Async(int value, int value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ITService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<APSWs.CompositeType> GetDataUsingDataContractAsync(APSWs.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface ITServiceChannel : APSWs.ITService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class TServiceClient : System.ServiceModel.ClientBase<APSWs.ITService>, APSWs.ITService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TServiceClient() : 
                base(TServiceClient.GetDefaultBinding(), TServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ITService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(TServiceClient.GetBindingForEndpoint(endpointConfiguration), TServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<APSWs.Ranking[]> GetRankingAsync()
        {
            return base.Channel.GetRankingAsync();
        }
        
        public System.Threading.Tasks.Task<string> GetRanking1Async()
        {
            return base.Channel.GetRanking1Async();
        }
        
        public System.Threading.Tasks.Task<APSWs.Cuadro[]> GetUltimosAsync()
        {
            return base.Channel.GetUltimosAsync();
        }
        
        public System.Threading.Tasks.Task<string> GetUltimos1Async()
        {
            return base.Channel.GetUltimos1Async();
        }
        
        public System.Threading.Tasks.Task<APSWs.Categoria[]> GetDataAsync(int value)
        {
            return base.Channel.GetDataAsync(value);
        }
        
        public System.Threading.Tasks.Task<string> GetData1Async(int value)
        {
            return base.Channel.GetData1Async(value);
        }
        
        public System.Threading.Tasks.Task<APSWs.Cuadro[]> GetCuadroAsync(int value)
        {
            return base.Channel.GetCuadroAsync(value);
        }
        
        public System.Threading.Tasks.Task<string> GetCuadro1Async(int value)
        {
            return base.Channel.GetCuadro1Async(value);
        }
        
        public System.Threading.Tasks.Task<APSWs.Cuadro[]> GetPartidosAsync(int value)
        {
            return base.Channel.GetPartidosAsync(value);
        }
        
        public System.Threading.Tasks.Task<string> GetPartidos1Async(int value)
        {
            return base.Channel.GetPartidos1Async(value);
        }
        
        public System.Threading.Tasks.Task<int> GuardarResultadoAsync(int value, string resultado, int ganador, int WO)
        {
            return base.Channel.GuardarResultadoAsync(value, resultado, ganador, WO);
        }
        
        public System.Threading.Tasks.Task<APSWs.Cuadro[]> GetH2HAsync(int value, int value2)
        {
            return base.Channel.GetH2HAsync(value, value2);
        }
        
        public System.Threading.Tasks.Task<string> GetH2H1Async(int value, int value2)
        {
            return base.Channel.GetH2H1Async(value, value2);
        }
        
        public System.Threading.Tasks.Task<APSWs.CompositeType> GetDataUsingDataContractAsync(APSWs.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITService))
            {
                return new System.ServiceModel.EndpointAddress("http://www.apusaq.com/WS/TService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ITService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ITService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ITService,
        }
    }
}
